sonar.organization=gabomur88

sonar.projectKey=gabomur88_github-actions-simple

sonar.projectName=github-actions-simple

sonar.sources=src
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=venv/**,dist/**,__pycache__/**
